services:
  - type: web
    name: recipehelper
    env: python
    plan: free
    buildCommand: ./render-build.sh
    startCommand: gunicorn --log-level debug --access-logfile - --error-logfile - app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: OPENAI_API_KEY
        sync: false
